pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Build step'
            }
        }
        stage('Test') {
            steps {
                echo 'Test step'
            }
        }
        stage('Deliver') {
            steps {
                echo 'Last step'
            }
        }
        stage('Done') {
            steps {
                echo 'Done step'
            }
        }
    }
}
